version: "3"

networks:
  monitoring:
    external: false
  traefik:
    external: true

volumes: 
  minio-storage: 
    external: true

services:
  minio-server:
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z
    networks: 
      - traefik
      - monitoring
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    labels:
      traefik.enable: 'true'
      traefik.docker.network: traefik
      traefik.http.routers.minio.entrypoints: websecure
      traefik.http.routers.minio.rule: Host(`minio.citygo.es`)
      traefik.http.routers.minio.tls.certresolver: acme
      traefik.http.services.minio.loadbalancer.server.port: '9000'
      traefik.http.routers.minio-console.entrypoints: websecure
      traefik.http.routers.minio-console.rule: Host(`minio-console.citygo.es`)
      traefik.http.routers.minio-console.tls.certresolver: acme
      traefik.http.services.minio-console.loadbalancer.server.port: '9001'
