version: "3"

networks:
  monitoring:
    external: true
  traefik:
    external: true

volumes: 
  minio-storage: 
    external: true

services:
  minio-server:
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z
    ports:
      - 9000
      - 9001
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ROOT_USER: $${{ secrets.MINIO_ROOT_USER }}
      MINIO_ROOT_PASSWORD: $${{ secrets.MINIO_ROOT_PASSWORD }}
      MINIO_REGION_NAME: 'eu-central-1'
      MINIO_BROWSER_REDIRECT_URL: https://console.opendata.citygo.es
      MINIO_SERVER_URL: https://opendata.citygo.es # MinIO S3 API
    command: server --console-address ":9001" /data
    labels:
      kompose.service.expose: "opendata.citygo.es,console.opendata.citygo.es"
      kompose.service.expose.tls-secret: "opendata-tls-secret"
      kompose.service.expose.ingress-class-name: "traefik"

